name: Update and Commit boards.json on Release

on:
  release:
    types: [published]

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure you're on the main branch (or your default branch)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update_boards.py script
        run: python update_boards.py
        # Ensure update_boards.py does not add .zip files to the repo

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add boards.json
          git commit -m "Update boards.json with release details"
          git push
