name: Update boards.json on Release

on:
  release:
    types: [published]

jobs:
  update-boards-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get release information and update boards.json
        run: |
          python -c "import requests, hashlib;\
          release_data = requests.get('https://api.github.com/repos/ropg/board_definitions/releases/146841975', headers={'Accept': 'application/vnd.github.v3+json'}).json();\
          tag_name = release_data['tag_name'];\
          assets = release_data['assets'];\
          source_zip = [asset for asset in assets if asset['name'].endswith('.zip') and asset['content_type'] == 'application/zip'];\
          if not source_zip:\
            raise Exception('Source code zip not found.');\
          source_zip = source_zip[0];\
          asset_url = source_zip['browser_download_url'];\
          asset_size = source_zip['size'];\
          response = requests.get(asset_url);\
          sha256_hash = hashlib.sha256(response.content).hexdigest();\
          with open('boards.json.editme', 'r') as file:\
            content = file.read();\
          content = content.replace('{tag}', tag_name).replace('{hash}', sha256_hash).replace('{filesize}', str(asset_size));\
          with open('boards.json', 'w') as file:\
            file.write(content);"
        shell: /usr/bin/bash -e {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add boards.json
          git commit -m "Update boards.json with release details"
          git push
