name: Update boards.json on Release

on:
  release:
    types: [published]

jobs:
  update-boards-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get release information and update boards.json
        run: python update_boards.py
        shell: /usr/bin/bash -e {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add boards.json
          git commit -m "Update boards.json with release details"
          git push
